### ISSUE TITLE
pip install antispoofing.lbptop does not work ( bob 1.3 installed)

### ISSUE THREAD

**Issue by StevenLobo2** [bioidiap/antispoofing.lbp#5]
Hello,

I have installed bob 1.3.0a0. I compiled the sources and installed it on python virtual environment. When I do pip install antispoofing.lbptop I get below error 

Collecting bob.ip.color (from antispoofing.utils>=1.1.3->antispoofing.lbptop)
  Using cached bob.ip.color-2.0.2.zip
(can't find)
…
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('bob.io.base')

bob.io.base is for bob_v2 right? Do we require both version of bob (1.3 and 2)? How to install both versions?

**Comment by siebenkopf** [comment]
Hi,

the bug you write is in the wrong package. Your problem is related to ``antispoofing.lbptop``, but this is package ``antispoofing.lbp``.

However, you don't need both versions of bob to install antispoofing.lbptop. Your problem is that you get the antispoofing.utils package in version >= 2, while you need it in version < 2 (bob 1 compatible). Simply changing the ``"antispoofing.utils >= 1.1.3"`` entry in the **setup.py** file to  ``"antispoofing.utils < 2"`` (and removing the current egg) should solve your problem.
